services:
  litestar_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Add any necessary environment variables here
      EXAMPLE_ENV: "value"
    ports:
      - "8000:8000"