services:
  litestar_server:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build # --buildbr0
    environment:
      # Add any necessary environment variables here
      EXAMPLE_ENV: "value"
    ports:
      - 8000:8000
    volumes:
      - ./src:/root/litestar_server/src

